# Generated by Django 4.1.7 on 2023-03-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_category_manufacturer_device_device_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_description',
            field=models.TextField(null=True),
        ),
    ]
